Add controllers
GlazyrinAV/java-shareit pull request #1
Opened 2023-06-19 09:55 UTC by GlazyrinAV

2023-06-19 18:59 UTC, EugeneLenkevich requested changes
Привет, Алексей, спасибо за PR

В целом все отлично, аккуратно и все на свих местах :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-06-19 18:59 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/MapperDto.java
> +public class MapperDto {
Объект, который производит маппинг можно, так же, сделать отдельным бином. Это позволит оформить все в единой(спринговой) парадигме и лишний раз избежать использования статических методов, которые являются жесткими ссылками.

То есть добавляем аннтоацию @Component или @Service, убираем static и инжектим в сервисы/контроллеры как и другие зависимости

Однако, это вопрос дискуссионный.
С другой стороны, в этом случае, мы пихаем в спринговый контекст дополнительный бин :)

Что думаешь на этот счет? :)

2023-06-19 18:59 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/MapperDto.java
> +public class MapperDto {
MapperDto 

название только не уверерн что самое удачное, давай подумаем, он маппит объекты типа Item, а что если его назвать, например, ItemMapper, будет ли это более информативно?

2023-06-19 18:59 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.findById(ownerID);
userService.findById(ownerID);

Не совсем понятно что делает эта строчка, судя по названию метода ищет, но результат никуда не присваивается. Если это проверка на существование, то почему бы не сделать примерно вот так :)
if (userService.isExist(id)) {
 .....
}

2023-06-19 18:59 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Collection<Item> itemList = itemStorage.findAllByUserID(ownerId);
findAllByUserID => findAllByUserId

так будет лчше соответствовать кодстайлу, посмтри, пожалуйста, и в других местах используется ли lowerCamelCase для имен переменных 
Вроде мелочь, однако влияет на восприятие кода при чтении, когнитивная нагрузка ниже кода все выполнено в едином стиле  :)

2023-06-19 19:26 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.findById(ownerID);
Добавил.
Считал, что методы findById и isExists по сути выполняют одно и тоже. При этом использование findById позволит сократить код, у него уже настроены исключения, не будет доп методов в интерфейсах.

2023-06-19 19:27 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/item/dto/MapperDto.java
> +public class MapperDto {
Переименовал

2023-06-19 19:28 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Collection<Item> itemList = itemStorage.findAllByUserID(ownerId);
это косяк

2023-06-19 19:38 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/item/dto/MapperDto.java
> +public class MapperDto {
Почитал эту статью - http://vanguardea.com/killing-the-helper-class-part-two/
Если принять во внимание, то что эта будет одной из наиболее часто используемых фичей во всем разрабатываемом приложении и она может в дальнейшем видоизменяться, то при прочих равных использование статик может затруднить юнит тестирование.

2023-06-20 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.findById(ownerID);
В таких ситуациях стоит искать баланс между минимализмом и понятностью. Тут мы вводим новый глагол в наш интерфейс, стороннему разработчику становится гораздо понятней, что речь идет именно о проверке существования записи.
Плюс, проверка существования может быть сделана гораздо дешевле чем получение всей сущности из хранилища, правда на нашем учебном примере это пока не видно :)

2023-06-20 03:32 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/MapperDto.java
> +public class MapperDto {
Статические методы не принадлежат классу и потому не участвуют в наследовании, соответсвенно часто они ломают иерархию наследования. Потому ими лучше особо не увлекаться :)

2023-06-20 03:33 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-06-20 03:46 UTC, merged