Add item requests
GlazyrinAV/java-shareit pull request #3
Opened 2023-07-18 18:57 UTC by GlazyrinAV

2023-07-19 19:14 UTC, EugeneLenkevich requested changes
Привет, Алексей, спасибо за PR

Ну и тесты, такие подробные :)
Отличная работа, только пару небольших моментиков отметил, посмотри комментарии ниже, пожалуйста

2023-07-19 19:14 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findByBooker_IdAndStartAfterOrderByStartDesc(int userId, LocalDateTime time, Pageable pageable);
OrderByStartDesc

В объекте Pageable уже есть возможность задать сортировку, попробуй, может получится указать через него,  чтобы не прибивать ее гвоздями указывая в самом запросе :)

2023-07-19 19:14 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/strategies/by/owner/FindByOwnerWaiting.java
> +            return bookingMapper.toDto(bookingRepository.findByItem_Owner_IdAndStatusEqualsOrderByStartDesc(userId, BookingStatus.WAITING));
В целом если не указано количество записей можно руками ограничивать количество некоторой константой или же вовсе ничего не возвращать. Чтоыб нечаяно не вытянуть пару миллиаров записей :)

И, кстати, обрати внимание что вроде как проверка параметров и создание объекта pageable  в нескольких местах дублируется, может вынести в утилитарный метод? :)

2023-07-19 19:14 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +@EqualsAndHashCode(exclude = {"item", "author", "text", "created"})
А не проще явно укзать поле (обычно это id для сущности из БД) по которому строить методы, это ж  проще и надежнее чем указывать те, что надо исключить, за этим же следить надо при добавлении новых полей :)

2023-07-19 19:14 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    Page<ItemRequest> findOthersRequests(int userId, Pageable pageable);
![image](https://github.com/GlazyrinAV/java-shareit/assets/109306643/fe1fbab1-69fe-4185-9315-9875f99b3c8c)

Опять таки, в pageable можно задат сортировку, лучше там и задать, не сортировать в самом запросе :)

2023-07-20 07:10 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/booking/strategies/by/owner/FindByOwnerWaiting.java
> +            return bookingMapper.toDto(bookingRepository.findByItem_Owner_IdAndStatusEqualsOrderByStartDesc(userId, BookingStatus.WAITING));
указал в методах без пагинации Top100

2023-07-20 07:16 UTC, GlazyrinAV commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +@EqualsAndHashCode(exclude = {"item", "author", "text", "created"})
как-то забыл об этом :)

2023-07-20 09:26 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-07-20 09:26 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/strategies/by/owner/FindByOwnerAll.java
> +        if (PageCheck.isWithoutPage(from, size)) {
ну, можно было просто в наш pageable подставить это значение, без доп методов :)

2023-07-20 11:16 UTC, merged